
version: '3.4'
services:
  cas:
    environment:    
      - SCONE_LOG=7
      - SCONE_MODE=HW  
      - SCONE_LAS_ADDR=las:18766
    image: iexechub/sconecuratedimages-iexec:cas-v3.0
    devices:
      - /dev/isgx:/dev/isgx 
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
      - target: 18765
        protocol: tcp
        mode: host
    container_name: cas
    networks:
      - local-network
  las:
    image: iexechub/sconecuratedimages-iexec:las-v3.0
    devices:
      - /dev/isgx:/dev/isgx
    ports:
      - target: 18766
        published: 18766
        protocol: tcp
        mode: host
    container_name: las              
    networks:
      - local-network
      
  scone:
    volumes:
      - /home/romain/iexecdev/maria-db-deploy:/home
    image: sconecuratedimages/public-apps:python-3.7.3-alpine3.10-scone3.0
    devices:
      - /dev/isgx:/dev/isgx
    container_name: scone
    command: sh -c 'apk add curl && tail -f'
    networks:
      - local-network

  secret-vault: 
    image: romainplt/secret-vault
    container_name: secret-vault
    ports:
      - 8080:8080
    devices: 
      - /dev/isgx
    volumes:
      - secret-vault:/tmp/secret-vault/data:rw
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx64m
      - SCONE_LAS_ADDR=las
      - SCONE_CONFIG_ID=session_secret-vault/secret-vault      
      - SCONE_LOG=7
      - SCONE_MODE=hw
      - SCONE_HEAP=2G
      - SCONE_CAS_ADDR=cas
      - SCONE_ALPINE=1
      - SCONE_FORK=1
      - SCONE_SESSION_ID=session_secret-vault
    networks:
      - local-network
       
  maria-db: 
    image: registry.scontain.com:5050/sconecuratedimages/apps:mariadb-alpine-scone3.0
    container_name: maria-db
    devices: 
      - /dev/isgx
    restart: 'always'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE= database
      - MYSQL_USER=user
      - JAVA_TOOL_OPTIONS=-Xmx64m
      - SCONE_LAS_ADDR=las
      - SCONE_CONFIG_ID=maria-db-session/maria-db      
      - SCONE_HEAP=2G
      - SCONE_LOG=7
      - SCONE_MODE=hw
      - SCONE_CAS_ADDR=cas
      - SCONE_ALPINE=1
      - SCONE_FORK=1
      - SCONE_SESSION_ID=maria-db-session
    #user: mysql
    networks:
      - local-network
     
volumes:
  secret-vault:
    external: true   
  maria-db:
    external: true
            
networks:
        local-network:
                external: true
