#!/bin/bash


	
####################################################################### VARIABLES


path_to_app=/home/romain/iexecdev/maria-db-deploy
path=$(pwd)
name_app=secret-vault
dockerfile=Dockerfile-trusted
image_name=romainplt/secret-vault
secret=
key=
scone_heap=2G
build_arg=build/libs/*.jar
passive=no

####################################################################### FUNCTIONS

usage()
{
	echo "  
	
	Run you app in a local CAS.
	
		./run_secret-vault [-tag] 
		
		./run_secret-vault -s mySecret -k myKey -i example/image -d my-dockerfile -b /path/to/*.jar -n my-app -p /path/to/app --scone-heap 2G 
		 
		
		-b --build-arg 	Path to jar file for docker.
					Default : build/libs/*.jar 
		-d --dockerfile     	Name of the file your docker build points to. 
					Default : Dockerfile-trusted
		-i --image-name     	App's image name for building in docker. 
					Default : romainplt/secret-vault 
		-k --key		Key to inject in session
		-n --name           	Your app's name need to be the one you use to run docker-compose. 		
					Default : secret-vault 
		-p --path-to-app    	Absolute path. You need to have a docker-compose in the folder you point. 	
					Default : ~/iexecdev/iexec-secret-vault-deploy
		-s --secret		Secret to inject in session
		
		
		--scone-heap     	Change SCONE_HEAP. xG giga / xM mega / xK kilo / x octets. 			
					Default : 2G
		"
}	

remove_docker_containers()
{	

	echo "Here are your current containers : "
	yesorno=yes
	while [ $yesorno = yes ]; do
		docker ps -a --format "table {{.Image}}\t{{.Names}}\t{{.Status}}"
		echo " "
		echo "Do you want to stop/rm one or several ? (y/n)"
		read answer

		if [ $answer = y ] || [ $answer = yes ] || [ $answer = Y ]; then
			yesorno=yes
			echo "write 'all' if you want to remove them all. Or write one name."
			read container
			
			if [ $container = all ]; then
				echo "Removing all containers ..."
				docker stop $(docker ps -a -q)
		                docker rm $(docker ps -a -q)
		                yesorno=no
			else
				echo "removing container $container"
				docker stop $container 
				docker rm $container
				echo " "
			fi
		else 
			yesorno=no
		fi
	done	
}

build_secret_vault()
{ 
	echo " "
	if [ $(docker ps -qa -f name=secret-vault) ]; then
		docker stop secret-vault						
		docker rm secret-vault
	fi
	cd $path_to_app
	./gradlew build
	cd $path_to_app
	rm dockerlogs.txt
	docker build --file $dockerfile --no-cache --build-arg JAR_FILE=$build_arg -t $image_name . >> dockerlogs.txt	
}

get_mr_enclave()
{
	cd $path_to_app
	mr_enclave=$(grep -i -A 2 'RUN SCONE_MODE=SIM SCONE_HEAP=2G SCONE_LOG=7 SCONE_HASH=1 SCONE_ALPINE=1 /usr/bin/java' dockerlogs.txt | sed -n 3p)
}

get_fspf_key_tag()
{
	cd $path_to_app
	fspf_tag1=$(grep '<FSPF_TAG>' dockerlogs.txt)
	fspf_tag1=${fspf_tag1%<*}
	fspf_tag=$(echo $fspf_tag1 | sed 's/.*>//')

	fspf_key1=$(grep '<FSPF_KEY>' dockerlogs.txt)
	fspf_key1=${fspf_key1%<*}

	fspf_key=$(echo $fspf_key1 | sed 's/.*>//')

}

create_session_secret_vault()
{
	cd $path
	sessionfile="session.yml"
	if [ -f "$sessionfile" ]; then
	        rm session.yml
	fi
	cp session.yml.template session.yml
	sed -i "s/%MR_ENCLAVE%/$mr_enclave/" session.yml
	sed -i "s/%FSPF_KEY%/$fspf_key/" session.yml
	sed -i "s/%FSPF_TAG%/$fspf_tag/" session.yml
	sed -i "s/%SECRET%/$secret/" session.yml
	sed -i "s/%KEY%/$key/" session.yml
	
	cat session.yml
	
}

create_session_maria()
{

	cd $path
	sessiondb="session_db.yml"
	session_client="session_client.yml"
	if [ -f "sessiondb" ]; then
		rm sessiondb.yml
	fi
	if [ -f "session-client" ]; then 
		rm session_client.yml
	fi
	
	export DBSESSION="MariaDBSession-1"
	export DBCLIENT="MariaDBClientSession-1"
	docker exec -it scone sh -c "scone session create --name=$DBCLIENT  --use-env scone-templates/mariadb/dbclient.yml"
	docker exec -it scone sh -c "scone session create --name=$DBSESSION --use-env scone-templates/mariadb/dbsession.yml"

}

start_cas_las_scone-cli()
{

	cd $path
	docker volume rm secret-vault
	docker volume create secret-vault
	docker network create local-network
	export volume=$path
	
	compose="docker-compose.yml"
	if [ -f "$compose" ]; then
	        rm docker-compose.yml
	fi
	cp docker-compose.yml.template docker-compose.yml
	sed -i "s+%VOLUME%+$path+" docker-compose.yml
	sed -i "s+%IMAGE%+$image_name+" docker-compose.yml
	sed -i "s/%SCONE_HEAP%/$scone_heap/" docker-compose.yml
	
	cat docker-compose.yml

	docker-compose up -d cas las scone
	mr_enclave=$(docker exec -it cas sh -c "SCONE_HASH=1 /usr/local/bin/cas")
	mr_enclave2=${mr_enclave%?}
	sleep 2
	trust=$(docker exec -it scone  sh -c "scone cas attest -G --only_for_testing-debug cas $mr_enclave2")
}

push_session_to_cas()
{
	cd $path
	rm sessionId.txt
	docker exec -it scone sh -c "cd home && curl -k -s --cert conf/client.crt --key conf/client-key.key --data-binary @session.yml -X POST https://cas:8081/session" >> sessionId.txt
	session_id=$(cat sessionId.txt | grep hash)
	session_id=${session_id%*??}
	session_id=${session_id:11}
	rm sessionId.txt 
	echo $session_id >> sessionId.txt
	rm session.txt
	docker exec -it scone sh -c "cd home && curl -k -s --cert conf/client.crt --key conf/client-key.key https://cas:8081/session/session_secret-vault" >> session.txt
}


up_secret-vault()
{
	cd $path
	
	echo " "
	echo "Running $name_app"
      	if [ $passive = "no" ]; then
      		docker-compose up secret-vault 
      	else
      		docker-compose up -d secret-vault
      	fi
}


####################################################################### SCRIPTS


if [ "$1" == "" ]; then
	usage
	exit
fi

while [ "$1" != "" ]; do
	case $1 in
		--scone-heap )
			shift
			scone_heap=$1
			;;
		-s | --secret )
			shift
			secret=$1
			;;
		-k | --key )
			shift
			key=$1
			;;
		-p | --path-to-app )
			shift
			path_to_app=$1
			;;
		-n | --name )
			shift
			name_app=$1
			;;
		-d | --dockerfile )
			shift 
			dockerfile=$1
			;;
		-i | --image_name )
			shift
			image_name=$1
			;;
		-b | --build-arg ) 
			shift
			build_arg=$1
			;;
		--passive )
			shift
			passive=$1
			;;
		-h | --help )
			usage
			exit
			;;
		* ) 	usage
			exit
			;;
			
	esac
	shift
done


remove_docker_containers
build_secret_vault
get_mr_enclave
get_fspf_key_tag
create_session_secret_vault
start_cas_las_scone-cli 	
push_session_to_cas
up_secret-vault


















