
version: '3.4'
services:
        cas:
                
                environment:    
                      - SCONE_LOG=7
                      - SCONE_MODE=hw
                      - SCONE_LAS_ADDR=las:18766
                image: iexechub/sconecuratedimages-iexec:cas-v3.0
                devices:
                      - /dev/isgx:/dev/isgx 
                ports:
                      - target: 8081
                        published: 8081
                        protocol: tcp
                        mode: host
                      - target: 18765
                        protocol: tcp
                        mode: host
                container_name: cas
                networks:
                      - local-network
        las:
                image: iexechub/sconecuratedimages-iexec:las-v3.0
                devices:
                      - /dev/isgx:/dev/isgx
                ports:
                      - target: 18766
                        published: 18766
                        protocol: tcp
                        mode: host
                container_name: las              
                networks:
                      - local-network
        scone:
                volumes:
                      - $VOLUME:/home
                image: sconecuratedimages/public-apps:python-3.7.3-alpine3.10-scone3.0
                devices:
                      - /dev/isgx:/dev/isgx
                container_name: scone
                command: sh -c 'apk add curl && tail -f'
                networks:
                      - local-network
        
networks:
        local-network:
                external: true
